name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  cyclic-imports:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-env
        with:
          python-version: '3.13'

      - name: check ghflowgen
        run: |
          python -c "import ghflowgen"

      - name: check ghflowgen.utils
        run: |
          python -c "from ghflowgen import utils"

      - name: check ghflowgen.version
        run: |
          python -c "from ghflowgen import version"
